// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'HomePage',
//   description: 'Generated by create next app',
// }
import styles from "./styles.module.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(styles);
  
  return (
    <main className={`mainContainer mx-auto mt-8 w-full sm:w-10/12 h-auto bg-tersiary bg-opacity-70 rounded-2xl text-center text-slate-50 py-8`}>
      {children}
    </main>
  );
}
